jobs:
  test:
    executor:
      name: node/default
      tag: '12.20'
    steps:
      - checkout
      - node/install-packages:
          with-cache: false
          override-ci-command: yarn install
      - run:
          command: yarn build
          name: Build
      - run:
          command: yarn test --coverage
          name: Tests
      - run:
          command: yarn lint
          name: Lint

version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  node-tests:
    jobs:
      - test
      

