name: Node.js CI

on: push

jobs:
  install:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        os:
          - ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: yarn test --coverage
    - run: bin/run --help
    - run: yarn test:codecov:upload
    - run: bin/run run . --fail=high
  linter:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn lint
      - run: yarn codecov
  runtime-test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    needs: [build, test, linter]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: yarn test --coverage
    - run: bin/run --help
    - run: yarn test:codecov:upload
    - run: bin/run run . --fail=high
  docker:
    runs-on: ubuntu-latest
    needs: runtime-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        env:
          CONTAINER_NAME: docker.pkg.github.com/dxheroes/dx-scanner/release
      - run: npm -g i .
      - run: dx-scanner run https://github.com/DXHeroes/dx-scanner --fail=off
      - run: docker build -f Dockerfile.github-action -t $CONTAINER_NAME .
